version: '3'
services:

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - "./portData:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - janusGraphEnvNetwork

  janusgraph:
    image: aleopold/docker-janusgraph:latest
    container_name: janusgraph
    ports:
      - "8182:8182"
    volumes:
      - "./janusConf:/janusgraph-0.2.0-hadoop2/conf"
    networks:
      - janusGraphEnvNetwork

  graphexp:
    image: aleopold/docker-graphexp:latest
    container_name: graphexp
    ports:
      - "8183:80"
    volumes:
      - "./graphexp:/usr/share/nginx/html"
    networks:
      - janusGraphEnvNetwork
  
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - janusGraphEnvNetwork
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    ports:
      - "9200:9200"
    volumes:
      - "./dataES:/usr/share/elasticsearch/data"
      - "./elasticConf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    networks:
      - janusGraphEnvNetwork
  
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    environment:
      - CASSANDRA_START_RPC=true
    ports:
      - "7000:7000"
      - "9042:9042"
      - "9160:9160"
    volumes:
      - "./dataCassandra:/var/lib/cassandra"
    networks:
      - janusGraphEnvNetwork

networks:
  janusGraphEnvNetwork:
    driver: bridge